package com.zhangyp.develop.HappyLittleBook.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhangyp.develop.HappyLittleBook.bean.ExpendLevelOneCate;
import com.zhangyp.develop.HappyLittleBook.bean.ExpendLevelTwoCate;
import com.zhangyp.develop.HappyLittleBook.bean.IncomeLevelOneCate;
import com.zhangyp.develop.HappyLittleBook.bean.IncomeLevelTwoCate;

import com.zhangyp.develop.HappyLittleBook.db.ExpendLevelOneCateDao;
import com.zhangyp.develop.HappyLittleBook.db.ExpendLevelTwoCateDao;
import com.zhangyp.develop.HappyLittleBook.db.IncomeLevelOneCateDao;
import com.zhangyp.develop.HappyLittleBook.db.IncomeLevelTwoCateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expendLevelOneCateDaoConfig;
    private final DaoConfig expendLevelTwoCateDaoConfig;
    private final DaoConfig incomeLevelOneCateDaoConfig;
    private final DaoConfig incomeLevelTwoCateDaoConfig;

    private final ExpendLevelOneCateDao expendLevelOneCateDao;
    private final ExpendLevelTwoCateDao expendLevelTwoCateDao;
    private final IncomeLevelOneCateDao incomeLevelOneCateDao;
    private final IncomeLevelTwoCateDao incomeLevelTwoCateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expendLevelOneCateDaoConfig = daoConfigMap.get(ExpendLevelOneCateDao.class).clone();
        expendLevelOneCateDaoConfig.initIdentityScope(type);

        expendLevelTwoCateDaoConfig = daoConfigMap.get(ExpendLevelTwoCateDao.class).clone();
        expendLevelTwoCateDaoConfig.initIdentityScope(type);

        incomeLevelOneCateDaoConfig = daoConfigMap.get(IncomeLevelOneCateDao.class).clone();
        incomeLevelOneCateDaoConfig.initIdentityScope(type);

        incomeLevelTwoCateDaoConfig = daoConfigMap.get(IncomeLevelTwoCateDao.class).clone();
        incomeLevelTwoCateDaoConfig.initIdentityScope(type);

        expendLevelOneCateDao = new ExpendLevelOneCateDao(expendLevelOneCateDaoConfig, this);
        expendLevelTwoCateDao = new ExpendLevelTwoCateDao(expendLevelTwoCateDaoConfig, this);
        incomeLevelOneCateDao = new IncomeLevelOneCateDao(incomeLevelOneCateDaoConfig, this);
        incomeLevelTwoCateDao = new IncomeLevelTwoCateDao(incomeLevelTwoCateDaoConfig, this);

        registerDao(ExpendLevelOneCate.class, expendLevelOneCateDao);
        registerDao(ExpendLevelTwoCate.class, expendLevelTwoCateDao);
        registerDao(IncomeLevelOneCate.class, incomeLevelOneCateDao);
        registerDao(IncomeLevelTwoCate.class, incomeLevelTwoCateDao);
    }
    
    public void clear() {
        expendLevelOneCateDaoConfig.clearIdentityScope();
        expendLevelTwoCateDaoConfig.clearIdentityScope();
        incomeLevelOneCateDaoConfig.clearIdentityScope();
        incomeLevelTwoCateDaoConfig.clearIdentityScope();
    }

    public ExpendLevelOneCateDao getExpendLevelOneCateDao() {
        return expendLevelOneCateDao;
    }

    public ExpendLevelTwoCateDao getExpendLevelTwoCateDao() {
        return expendLevelTwoCateDao;
    }

    public IncomeLevelOneCateDao getIncomeLevelOneCateDao() {
        return incomeLevelOneCateDao;
    }

    public IncomeLevelTwoCateDao getIncomeLevelTwoCateDao() {
        return incomeLevelTwoCateDao;
    }

}
