package com.zhangyp.develop.HappyLittleBook.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhangyp.develop.HappyLittleBook.bean.IncomeLevelTwoCate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INCOME_LEVEL_TWO_CATE".
*/
public class IncomeLevelTwoCateDao extends AbstractDao<IncomeLevelTwoCate, Long> {

    public static final String TABLENAME = "INCOME_LEVEL_TWO_CATE";

    /**
     * Properties of entity IncomeLevelTwoCate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OneCateId = new Property(1, Long.class, "oneCateId", false, "ONE_CATE_ID");
        public final static Property CateName = new Property(2, String.class, "cateName", false, "CATE_NAME");
    }


    public IncomeLevelTwoCateDao(DaoConfig config) {
        super(config);
    }
    
    public IncomeLevelTwoCateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INCOME_LEVEL_TWO_CATE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ONE_CATE_ID\" INTEGER," + // 1: oneCateId
                "\"CATE_NAME\" TEXT);"); // 2: cateName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INCOME_LEVEL_TWO_CATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IncomeLevelTwoCate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long oneCateId = entity.getOneCateId();
        if (oneCateId != null) {
            stmt.bindLong(2, oneCateId);
        }
 
        String cateName = entity.getCateName();
        if (cateName != null) {
            stmt.bindString(3, cateName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IncomeLevelTwoCate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long oneCateId = entity.getOneCateId();
        if (oneCateId != null) {
            stmt.bindLong(2, oneCateId);
        }
 
        String cateName = entity.getCateName();
        if (cateName != null) {
            stmt.bindString(3, cateName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IncomeLevelTwoCate readEntity(Cursor cursor, int offset) {
        IncomeLevelTwoCate entity = new IncomeLevelTwoCate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // oneCateId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // cateName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IncomeLevelTwoCate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOneCateId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCateName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IncomeLevelTwoCate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IncomeLevelTwoCate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IncomeLevelTwoCate entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
